### ISSUE TITLE
jest.useFakeTimers no longer works

### ISSUE THREAD

**Issue by lbargery** [kayahr/jest-environment-node-single-context#13]
Hi,

I just discovered this (very helpful!) package after stumbling across the jest issue here https://github.com/jestjs/jest/issues/2549

My issue was that in a test I was getting different behaviour from a mongoose library that use instanceof Function. However, when installing your package I've found that jest.useFakeTimers no longer works. Is that expected? If so, is there any way around this? Would value some advice on how best to mock time now!

Thanks

**Comment by kayahr** [comment]
Never used Jest's fake timers but I think/hope I managed to implement them. I tried some examples from the Jest documentation and they seem to work now.

Please try the new version 29.3.0 and let me know if fake timers work now as expected.

**Comment by lbargery** [comment]
Seems to work! Thanks so much for the ultra quick fix!! :)
