### ISSUE TITLE
Jest 27 support

### ISSUE THREAD

**Issue by lydell** [kayahr/jest-environment-node-single-context#5]
Hi! Thanks for making this package!

There’s a problem in Jest 27:

```
Test environment found at "/Users/lydell/project/node_modules/jest-environment-node-single-context/SingleContextNodeEnvironment.js" does not export a "getVmContext" method, which is mandatory from Jest 27. This method is a replacement for "runScript".
Test environment found at "/Users/lydell/project/node_modules/jest-environment-node-single-context/SingleContextNodeEnvironment.js" does not export a "getVmContext" method, which is mandatory from Jest 27. This method is a replacement for "runScript".
Test environment found at "/Users/lydell/project/node_modules/jest-environment-node-single-context/SingleContextNodeEnvironment.js" does not export a "getVmContext" method, which is mandatory from Jest 27. This method is a replacement for "runScript".
Test environment found at "/Users/lydell/project/node_modules/jest-environment-node-single-context/SingleContextNodeEnvironment.js" does not export a "getVmContext" method, which is mandatory from Jest 27. This method is a replacement for "runScript".
 FAIL  tests/Errors.test.ts
  ● Test suite failed to run

    Jest worker encountered 4 child process exceptions, exceeding retry limit

      at ChildProcessWorker.initialize (node_modules/jest-worker/build/workers/ChildProcessWorker.js:193:21)
```

Just thought I’d let you know!

**Comment by kayahr** [comment]
Already looked into this issue and so far I have no solution. Jest moved the script running  (which is the crucial part for switching to single context) from the environment to the the runtime so I can no longer override the behavior. 

https://github.com/facebook-atom/jest-electron-runner has the same problem (and some more) with Jest 27. I'm curious how they solve it.

If anyone has any idea how to fix this, please let me know.

**Comment by kayahr** [comment]
Just published a new release which now works with Jest 27. Solution is a little bit hacky but better than copying a lot of code from Jest.

**Comment by jabir-hussain** [comment]
> Just published a new release which now works with Jest 27. Solution is a little bit hacky but better than copying a lot of code from Jest.

Which exact version has the fix? Because I am using {"jest": "^27.4.7"} and the issue is still there.

**Comment by kayahr** [comment]
Major version 27 of jest-environment-node-single-context is meant for Jest 27. Minor/patch versions don't matter here. But I just updated the dependencies to jest 24.4.7 and published v27.2.1 of my project. The unit tests are still working fine.

If it is not working for you then I suggest opening a new issue with minimal example code and jest config so I can try to reproduce the problem.

**Comment by Divide-By-0** [comment]
I'm getting the original error with these packages:    
    "jest": "^24.5.0",
    "jest-cli": "^27.5.1",
    "jest-environment-jsdom": "^27.5.1",
    "jest-environment-jsdom-fourteen": "^1.0.0",
    "jest-environment-node": "^27.5.1",
    "jest-resolve": "24.8.0",
    "jest-runtime": "^27.5.1",
    "jest-watch-typeahead": "0.3.1",
    "jest-puppeteer": "^4.4.0",
    "@jest/core": "^27.5.1",
    "@jest/transform": "^27.5.1",
    "babel-jest": "^27.5.1",

Any idea what the issue could be? I tried `yarn add -W jest@24.4.7` but it didn't work, maybe since jest/core was still new?

**Comment by kayahr** [comment]
As I said, you need Jest 27. You use 24 which is way too old.

**Comment by xtremebiker** [comment]
For me, the problem was that I was using an older version of ts-jest.
