### ISSUE TITLE
TypeError: this._environment.runScript is not a function

### ISSUE THREAD

**Issue by alexkilgour** [kayahr/jest-environment-node-single-context#8]
Thanks for providing this module, it seems exactly what I am looking for as I have the same issue detailed in [this ticket](https://github.com/sass/sass/issues/3235). I have followed the same steps but am currently getting the following error at the moment:

```
 Test suite failed to run

    TypeError: this._environment.runScript is not a function

      at Runtime._execModule (node_modules/jest-runtime/build/index.js:856:41)
```

**Comment by kayahr** [comment]
This isn't much information to work with. Maybe you can provide a minimal example NPM project which can be used to reproduce this problem?

**Comment by kayahr** [comment]
Closing because lack of feedback.
